## 블로그 서버 설정 ############################################
baseurl: ""
url: "https://jix98.github.io"

## 블로그 기본 정보 ############################################
title: JIXBlog
email: me981026@outlook.kr
twitter_username: me981026
github_username:  jix98

markdown: kramdown
theme: minima
